[package]
name = "parsemon"
version = "0.1.0"
authors = ["Sebastian Jordan <sebastian.jordan.mail@googlemail.com>"]
edition = "2018"

[lib]
name = "parsemon"
crate-type = ["cdylib"]

[dependencies.pyo3]
features = ["extension-module", "abi3"]
version = "0.13.*"
